language: ruby
sudo: false
gemfile: nubis/travis/Gemfile
cache:
  bundler: true
  directories:
  - "${HOME}/bin"
addons:
  apt:
    sources:
    - debian-sid
    packages:
    - shellcheck
script:
- travis/run-checks
notifications:
  slack:
    secure: Mop2UxfGDXWcETYYw4RhnCgNdlq4nohgsLf/CJXImt5+fJX/smXdi+/v7W7/vt/6RhgWxeQp4uUybjHEPAhGx8/J3IrvIz/qPbXHjBK8TcU5F2oCMNp3v21nYS3U81nDxcUSIlDc5WnpVBaxgo5aelwRdYhXHowDVIPpdYQRWx8=
